fastai/fastbook

- 14_deep_conv.ipynb
Went through and briefly proofread chapter 14 on deeper convnets; all changes are related to grammar.
The final sentence in the chapter, which lies in the **Further research** subsection, doesn't actually have an action item attached to it:
> Batch normalization isn't defined for a batch size of one, since the standard deviation isn't defined for a single item. 
Should there be an invitation to explore alternate ideas, e.g., [Group Normalization](https://arxiv.org/abs/1803.08494)?
> Quick proofread of chapter 14

- 15_arch_details.ipynb
Replace "transfert learning" with "transfer learning"
> Correct spelling 15_arch_details - transfert to transfer

- 02_production.ipynb
- 03_ethics.ipynb
Hi, 
Here are some more recommendationsI found. Is it easier to have 1 long list, or split into separate ~5 change requests?
1) I think "rigourous" is not a real word. Did a quick Google search
org: We are not aware of any rigourous work done
chg: We are not aware of any **rigorous** work done
2) added a "w", and also fixed the link
org: they have as this book as written
chg: they have **was** this book as written
org: on the http://book.fast.ai[book website]
on the **[book website](http://book.fast.ai)**
3) stretch -> stretched, and added an as
org: If we squished or stretch the images then they end up unrealistic shapes,
chg: If we squished or **stretched** the images then they end up **as** unrealistic shapes,
4) "to" to "on"
org: To tell fastai we want to use these transforms to a …
> more ch2 typos

- 01_intro.ipynb
"Them" should be removed from "This is what you will learn how to build **them** in this book."
> Remove unnecessary word "them" in 01_intro.ipynb, line 160

- 01_intro.ipynb
In "The best _choice_ for GPU servers for use with this book **change** over time", the choice is what is changing, so it should be **changes**
> Change "change" to "changes" in 01_intro.ipynb, line 426

- 01_intro.ipynb
Line 1578: comma isn't needed
Line 1718: "higher levels" to "higher-level"
Line 1778: "it worked so well that *had* led" -> "it worked so well that *it* led"
Line 1875: remove space after terms
Line 2191: remove extra set of parentheses around link so it works
I can explain the other changes too if needed.
> Writing and formatting fixes, 01_intro.ipynb

- 06_multicat.ipynb
Looks like the BIWI dataset is not at the same page anymore.
I think that the reason is that the first author had the dataset page in his personal section of the ETH site, and he's not there anymore (apparently he works at Apple now). 
This is the best approximation I could find, although there is no download link anymore.
> FIX Biwi dataset link

- 02_production.ipynb
Changes by line number:
50: comma not needed
68:  "get real experience of" > "get the real experience of" 
85: hyphenate buy-in
96: add comma for easier reading
110: remove "there"
126: "less" to "fewer"
142: remove repeated word "generating" (already said it earlier in sentence)
160: change "and output" to "with output" to make it clear that "output" is a noun, not a verb
162: Add comma for easier reading
190: Add comma
192: "familiar with its products" > "familiar with the products" because "its" didn't refer to anything
229: change comma to colon
263: remove comma
270: "As at" to "At"
277ish: remove cell that is duplicated below
(following line numbers refer to newer file)
305: capitalize Jupyter
532: capitalize Jupyter
559: pluralize ("parenthesis" to "parentheses")
562: fix …
> Writing fixes, 02_production.ipynb

- README.md
I think being able to fire up the notebooks right away would make this great resource even more accessible.
> Add Binder badge to README to launch notebook fast

- app_jupyter.ipynb
Corrected the spelling of beginning in the given line: This command is always called together at the `beggining` of every notebook of the fast.ai course
> Minor typo fix in app_jupyter.ipynb

- 10_nlp.ipynb
1. Introductory paragraphs of notebook:
Location: Third paragraph from start of notebook, last line.
Search: "In the case of the IMDb **datset**, there will"
Changes: datset > dataset
2. Introductory paragraphs of notebook:
Location: Sixth paragraph from start of notebook, first line.
Search: "known as the Universal Language Model Fine-tuning (ULMFit) **approqch**. The paper showed"
Changes: approqch > approach
3. Training a Text Classifier:
Location: First paragraph, first line.
Search: "beginning of this chapter, **thare** are two steps"
Changes: thare > there 
4. Saving and Loading Models:
Location: Last paragraph, last line.
Search: "use it to fine-tune a **clasifier** using the IMDb sentiment"
Changes: clasifier > classifier
5. Disinformation and Language Models:
Location: Third …
> Updated some minor typos in '10_nlp.ipynb' (Markdown cells only)

- 10_nlp.ipynb
Change `. this` to `. This`. I'm not sure if typo fixes are still relevant since the book is published but I found it while reading so I just thought I'd make the PR.
Feel free to close if no longer relevant
> Minor Typo in 10_nlp.ipynb

- 04_mnist_basics.ipynb
28 x 28 = "784", opposed to written "768". 
(guessing where this 768 comes from?). Already present in last year edition.
> Typo on 04_mnist_basics.ipynb

- README.md
removed unnecessary commas from:
'San Francisco from March 2020,'
'know that their actions are not allowed,'
'they would be hurting the community,'
Also fixed:
'please specify the name of the file and very brief description...' to 'please specify the name of the file and a very brief description'
> grammar correction to README.md

- 04_mnist_basics.ipynb
file: **04_mnist_basics.ipynb** 
fix: Small misspelling -  "**Backward** pass"  is misspelt as "**Backard** pass"
> Chapter 4 misspelling - 'backard pass' -> 'backward pass'

- 01_intro.ipynb
- 12_nlp_dive.ipynb
Fixed typo in 01_intro.ipynb as described in #241. Also fixed tanh formula as described in #273
> Fixing tanh formula and typo in 01_intro

- 09_tabular.ipynb
The model `m` gives an error while running, which says input sizes are not matching. 
I'm not sure if its okay to change the Python version, since that's what was running on my system. This is my first ever contribution, so please let me know if something's wrong.
> typo in NN section of 09_tabular.ipynb, referencing to wrong model 'm'

- 03_ethics.ipynb
The current link (https://www.scu.edu/ethics-in-technology-practice/conceptual-frameworks) returns a 404.
Based on an online search, the new link seems to be https://www.scu.edu/ethics-in-technology-practice/ethical-lenses/.
Please correct me if I'm wrong.
> Fix link to Markkula's Ethical Lenses

- 16_accel_sgd.ipynb
The 'sqr_avg' returned by the average_sqr_grad function is missing the (1-sqr_mom) term. 
a quick fix. 
cc: @jph00
> 16_accel_sgd: Fixed average_sqr_grad function

- 12_nlp_dive.ipynb
Hello,
I believe that you have 2 bugs in the LSTMCell code.
The first one is the `torch.stack` which, I think, should be `torch.cat` instead. This will create the intended tensor with the dimension of `n_in + n_hid` as mentioned in the book. 
The second one is usage of the `outgate` variable name which is not defined. It should be replaced with the `out` variable which is defined on the above line.
I am providing a custom model implementation based on the `LMModel4` (page 385) so that you can verify the new changes. The data that is fed into this model is exactly the same as the one in the book.
```
class LSTMModel(nn.Module):
def __init__(self, vocab_sz, n_hidden, bs=64):
super(LSTMModel, self).__init__()
self.i_h = nn.Embedding(vocab_sz, n_hidden)
self.lstm = LSTMCell(n_hidden, …
```
> fixed incorrect method call - torch.stack should be torch.cat, and fixed incorrect variable name

- 17_foundations.ipynb
its just "wat" -> "way". Amazing book though.
> fix typo in notebook 17

- 04_mnist_basics.ipynb
A definition of MSE loss function lacks square operation, which may be misleading.
> 04_mnist_basics: MSE lacks .sqrt()

- 02_production.ipynb
- utils.py
Hi FastAI team,
There have been some recent updates to the Bing Image Search API, and 02_production.ipynb no longer works out of the box as a result. There has been some discussion about this over on the forums over the past few months:
https://forums.fast.ai/t/02-production-permissiondenied-error/65823/19
I don't see any pull requests created yet, so I went ahead and proposed the following changes: 
1. Update search_images_bing() function in utils.py
2. Update the call to download_images in 02_production.ipynb
> 02_production: Updates needed for new Bing Image Search API

- 04_mnist_basics.ipynb
Found typo "experssion" instead of "expression" in markup above mnist_distance function cell
> 04_mnist_basics typo

- 09_tabular.ipynb
Based on context, `m2` should be used instead of `m`.
> typo-fix-for-cp9

- 02_production.ipynb
Thank you for fastai, it's so helpful/interesting
When going through the notebook 02_production I tried to install voila. It looks like the instructions no longer work, so I've updated them.
I'm using the paperspace console for fastai
> Fix voila install instructios

- 06_multicat.ipynb
The order of "inputs" and "1-inputs" is reversed in the "torch.where" call. I also checked against the mnist_loss function in ch4, which has the correct order. Please double check this as I may be mistaken.
> Fix binary_cross_entropy function in 06_multicat.ipynb

- 09_tabular.ipynb
#338 fixed a bug in the LSTM cell where torch.cat should be used instead of torch.stack
The questionnaire should be updated too because it refers incorrectly to torch.stack
My very first PR, I hope it's fine!
> Fix questionnaire: torch.stack->torch.cat

- 13_convolutions.ipynb
Hi Jeremy and Sylvain!
First of all, thank you for the great work! The library, the book, and the course are well-written and simply amazing! I, now, recommend your book to everyone who asks me about where to start with AI.
In one of the examples from the chapter 13 we have the following code:
```python
def conv(ni, nf, ks=3, act=True):
layers = [nn.Conv2d(ni, nf, stride=2, kernel_size=ks, padding=ks//2)]
layers.append(nn.BatchNorm2d(nf))
if act: layers.append(nn.ReLU())
return nn.Sequential(*layers)
```
We have batch norm added before the activation function but the text suggests that we should be normalizing activations.
> Batch normalization (often just called batchnorm) works by taking an average of the mean and standard deviations of the activations of a layer and using those to …
> fix: 13_convolutions.ipynb - we should be normalizing activations

- 08_collab.ipynb
In the last_skywalker toy example only two of the three values are explicitly mentioned which could cause confusion.
> completing explanation for last_skywalker example in 08_collab

- 09_tabular.ipynb
- clean/09_tabular.ipynb
As `saleElapsed` is now floating point the variable is no more missdetected as categorical. Hence the workaround to fix the classification must be removed.
With these changes the notebook runs once again without throwing errors.
@jph00
> Update 09_tabular to fastai v2.2.7

- 13_convolutions.ipynb
The example convolution calculation in Chapter 13 (see below) is wrong. 
The kernel being referred to in this example is instantiated earlier as such:
``` python
top_edge = tensor([[-1,-1,-1],[0,0,0],[1,1,1]]).float()
```
Therefore the correct sum would be -a1-a2-a3+a7+a8+a9. This PR addresses this.
> Fix matrix calculation in Chapter 13

- clean/02_production.ipynb
File name: `clean/02_production.ipynb`
Change description:
1. Importing os to read the Azure key environment variable
2. Correcting the contentUrl response parameter while reading the response from Bing image search
> Fixing os import and bing search result response parameter

- utils.py
json module is used in ddg search and so that method fails since json module is not imported
> Fix missing import for json module

- 04_mnist_basics.ipynb
This reverts commit 665c2384677aa1d42a364e93f8edcfea2ee71bc5 and PR #327.
The PR being reverted is incorrect since the original code contained the correct definition of MSE. Adding the `sqrt()` changes it to RMSE with the knock on effect being the loss is much smaller and the resulting parameter updates becoming negligible. See below of what the prediction plots in Step 6 become vs what they should be (i.e. the original plots still in the notebook)
Plot when using MSE with `.sqrt()` (i.e. the RMSE)
Original with correct definition of MSE
Also should I manually update the clean notebook as well? Or does that happen automatically somewhere else?
> Revert "04_mnist_basics: MSE lacks .sqrt() (#327)"

- 04_mnist_basics.ipynb
In chapter 4 about MNIST, there's an error in the book, which is not apparent in the cleaned notebook. Before the introduction of the sigmoid function, the threshold on the linear outputs is set to `0.5` instead of `0.0`.
> Correct ch.4 MNIST: set threshold to 0.0 when not using sigmoid

- 04_mnist_basics.ipynb
> "many batches" -> "mini-batches"

- 01_intro.ipynb
The link in chapter 1 to the datasets provided by fast.ai was broken. This pull request fixes the broken link.
Previously: https://course.fast.ai/datasets
Now: https://docs.fast.ai/data.external.html#datasets
> Fix broken link in ch1 to fast.ai datasets
