fastai/fastbook

- 01_intro.ipynb
See diff & https://www.doi.org/doi_handbook/3_Resolution.html#3.8 ;-)
> Hyperlink DOI to preferred resolver

- 01_intro.ipynb
**They** realised that a simplified model of a real neuron could be represented using simple addition and thresholding.
> spelling - The to They

- 21_learner.ipynb
What we really saying is
now
What we are really saying is
> Fix spelling in 21_learner.ipynb

- 01_intro.ipynb
replaces "model model" with "model"
> fix minor typo

- 01_intro.ipynb
Changed "other" for  "order" in: "The program's inputs are values that it processes in other to products its results"
> "In order to"

- 03_ethics.ipynb
Other note on the content:
In the section on Representational Bias : the quote from the paper says "may compound these imbalances"  - I wondered if this is then feedback or some other mechanism. The next lines are such that I think it is distinct - but I've not understood whats happening? I think the y axis is such that a 45degree slope would mean balanced predictions - is that right?
positive examples on increasing diversity are always great- here's one in the software industry : https://research.curtin.edu.au/projects-expertise/institutes-centres/autism/
> proofread ethics

- 04_mnist_basics.ipynb
- README.md
replace "very" with "vary" to correct meaning
replace "at" with "add" to indicate summing correctly
> Correct two spelling errors in 04_mnist_basics

- 05_pet_breeds.ipynb
proofreading(changing from "we don't to consider" to be"we don't need to consider" )
> proofreading(missing word in "we don't to consider")

- 01_intro.ipynb
> Minor Typos Chp 1

- 04_mnist_basics.ipynb
Corrected 2 spellings and updated learning rate value in prose to match with code.
> Fixed minor typos

- 14_resnet.ipynb
query on the questionaire - is adaptive pooling covered in the text? My reading was more - we want to do average pooling and there's some pytorch thing to handle different sizes that we're not too worried about it. then i saw the question - so maybe I'm missing something there
the 1x1 convolution - I think the approach here would work great in a course - but not sure in the book. If someone doesnt try it out or know what a dot product is, I think they'll just skim by and not really understand the question at the end of chapter. 
another exercise that might be nice - suggest the reader print out what you have created and said is a resnet 18 and a resnet 50 and they can try count the layers...
> proofread ResNet

- 13_convolutions.ipynb
I'm sleepy for this one, so sure I missed stuff.
Is it an accident that left_edge is [-1,1,0] not [-1,0,1] rows like top_edge'? I considered changing it, or even leaving both (maybe even a 3rd case with -2,0,2 in the middle) for reader to play - so thats an idea for you to consider
I gotta ask - I think some of these are using color others colour. math and maths etc go Aussie :)
The final further research item #4 reads as a statement - there's no variance for a batch size 1. what was the intended research?
> proofread convolutions

- 02_production.ipynb
> Minor Typos Chp2

- 04_mnist_basics.ipynb
- 20_conclusion.ipynb
I havent touched them - but I'll mention the mix of math/maths, color/colour, check/cheque which are in here. US/Intl to be handled later?
an option under broadcasting is to mention if the reader ever used Matlab, they likely are familiar with it.
unless i missed it, I don't think this notebook set a seed?
the quadratic function solver used LR 1E-5. there was a previous line that suggested 1E-3 is a common lower bound. not sure if you want to mention it. I see anything larger explodes. maybe a further research option at the end of the chapter to test other values on that example?
def batch_accuracy(xb, yb) uses sigmoid. the above cell doesn't and the reader who understood the difference between metric and loss may be confused why you transformed this here. it won't affect the result, but …
> proofread mnist

- 11_midlevel_data.ipynb
Should call .setup() instead of .setups()
> fixed a typo in chap11

- 01_intro.ipynb
Since the following point was "Computer vision", and not "CV" :slightly_smiling_face:
> Expand "NLP" into "Natural language processing"

- 05_pet_breeds.ipynb
Also, I think these phrases need a revision:
"Often, data scientists work with data with which they are not familiar as domain experts me"
"we first have to understand what the actual data and activations that are loss function is seen look like"
> Some typos

- 01_intro.ipynb
Original:
>There a number of powerful concepts embedded in this short statement:
After:
There **are** a number of powerful concepts embedded in this short statement:
> Chapter 1 intro minor correction

- 01_intro.ipynb
The second "rather" is not needed in "somebody who would rather get their hands dirty building stuff **rather** than spend years learning abstract concepts"
> Remove unnecessary word "rather", 01_intro.ipynb, line 220

- 01_intro.ipynb
The 's should be removed from "That means **that's** if you're teaching baseball"
> Change "that's if" to "that if" in 01_intro.ipynb, line 266

- 01_intro.ipynb
The "like" should be removed from "it's not as hard as it looks **like**"
> Remove unnecessary word "like" in 01_intro.ipynb, line 391

- 01_intro.ipynb
"containing" should be removed from "A dataset **containing** called the Oxford-IIT Pet Dataset that contains 7,349 images"
> Remove extra word "containing" in 01_intro.ipynb, line 511

- 04_mnist_basics.ipynb
- 09_tabular.ipynb
a tiny typo and a potential small text edit.
> tiny typo n edit

- 01_intro.ipynb
The wording of "_revisit_ our image classification problem _into_ Samuel's framework" doesn't work because it basically says "_revisit_ something _into_ something". It makes more sense to say "_revisit_ our problem _using_ the framework", but other words would also work in the place of _using_
> Change "revisit ... into" to "revisit ... using", 01_intro.ipynb

- 05_pet_breeds.ipynb
1) your -> you
org: the vast majority of the datasets your work with
chg: the vast majority of the datasets **you** work with
2) added ,
org: When we see it in that format looks a bit boring;
chg: When we see it in that format**,** it looks a bit boring;
3) deepest -> shallowest
org: The deepest layers of our pretrained model might not need as high a learning rate as the last ones
chg: The **shallowest** layers of our pretrained model might not need as high a learning rate as the last ones
> grammar changes

- 11_midlevel_data.ipynb
> remove duplicate cell

- 11_midlevel_data.ipynb
I'm not sure the output must be changes or the inputs, So made this as a separate PR.
> fix output value

- 05_pet_breeds.ipynb
Small changes: 
- the first chapter, we didn't specified -->> the first chapter, we didn't specify
- were looking for the validation loss -->> we're looking for the validation loss
> Update 05_pet_breeds.ipynb Small typos and grammar

- app_jupyter.ipynb
Purpose of each change with line number:
15: capitalize
22: pluralize
24: remove word
38: 
colon works better there
capitalize, clarification of "it"
typo
65: needs comma
67: wrong word choice
141: 
wrong 'its'
'if' not needed
159:
capitalize
fix idiom
165: change tense to make consistent with other bullets
175: colon better than comma here
191: capitalize header words for consistency across the notebook
356: "I am watching you." has no purpose here other than maybe as a joke about the cat, but is very confusing. It sounds like "I (the author) am watching you". 
384: capitalize header words for consistency across the notebook
402: capitalize header words for consistency across the notebook
409: capitalize, make clear distinction between the server and a notebook
418: capitalize header …
> Fix writing errors, app_jupyter.ipynb

- 08_collab.ipynb
Change: 
matrix modification -->> matrix multiplication
> Update 08_collab.ipynb Small change

- 11_midlevel_data.ipynb
> [11_midlevel_data] Suggested edits for clarity and brevity.

- 03_ethics.ipynb
133: "even although" to "even though"
165: "go pretty bad" to "go pretty badly"
197: "as best as they could" to "the best they could"
223: add hyphens to "out of domain"
227: comma to colon after "default parameters"
241: add hyphen to "cross disciplinary"
243: add period at end of sentence
245: rework end of sentence to remove extra commas
344: fix plural in "transparency...makes"
348: "such as" to "such a"
350: "their" to "its" (referring to "metric", or maybe "a company")
447: remove hyphen from "mis-step"
477: slightly move comma, add "that" (to fix grammar)
566: add comma after "However"
582: hyphenate "easy to see"
598: improve grammar
633: add "whereas" to make meaning clearer
678: add "to" for parallel structure of sentence, change comma to colon
722: add "the" for readability …
> Writing fixes, 03_ethics.ipynb

- 03_ethics.ipynb
Changed "curtesy" to "courtesy"
> Small typo, 03_ethics.ipynb

- environment.yml
Added environment.yml file to make it easier for conda users to get started.
> Added environment.yml

- clean/utils.py
There is no utils.py in the "clean" folder. I am just adding the same.
> Adding utils.py to the stripped version "clean"

- 02_production.ipynb
1. Removed the duplicate paragraph "To download images with Bing Image
Search..." under the `Gathering Data` > `cleon` section.
2. Added hyperlinks to https://book.fast.ai for the phrase
"book's website". Specifically, in the `Gathering Data` and `State of
deep learning` sections.
3. Corrected the hyperlink to https://book.fast.ai for the phrase
"book's website" in the `Deploying your app` section.
> Updated typos in `02_production.ipynb` (markdown cells only).

- 11_midlevel_data.ipynb
1) neural network application -->> neural network applications
> Update 11_midlevel_data.ipynb Small change

- 16_accel_sgd.ipynb
1) explorea little — explore a little
2) they all their own — they all have their own
3) to udpate -- to update
> Update 16_accel_sgd.ipynb Small changes

- 19_learner.ipynb
1) and test it works -->> and test if it works
2) such such any time -->> such that any time
> Update 19_learner.ipynb Small changes

- 17_foundations.ipynb
1) the gradient we -->> the gradients we
> Update 17_foundations.ipynb Small typo

- 17_foundations.ipynb
1) and want compute -->> and want to compute
> Update 17_foundations.ipynb Small change

- 15_arch_details.ipynb
1) but will look -->> but we will look
2) at each line of code in `forward`in turn -->> at each line of code in `forward` in turn
> Update 15_arch_details.ipynb Small changes and spacing

- 01_intro.ipynb
Typo "Trianing Time" to "Training Time" change
> Typo "Trianing Time" to "Training Time" change

- 04_mnist_basics.ipynb
> Fix sentence about abs in mnist_distance

- README.md
- README_es.md
This pull request applies the following changes:
- A new README_es.md file that translate the README.md file into Spanish
- A link to README_es.md in README.md
> Adds a translated readme file in Spanish

- 05_pet_breeds.ipynb
- 09_tabular.ipynb
Opening a new PR for that, I believe that `m` should be `m2`, otherwise wrong number of columns is reported.
> Fix ch09 model choice

- 04_mnist_basics.ipynb
Get it? 
🦗
I'll be here all night.
> A "smll" typo fix

- 16_accel_sgd.ipynb
Please check if the fix for exception order is proper.
> Ch16 Fixes

- 02_production.ipynb
- clean/02_production.ipynb
Removed ambiguity in both versions of notebook 02_production about the Bing Search API key. (#318)
> Fix: Linked to the right Microsoft page raised in (#318)

- README_zh.md
reference: [document guide about Chinese](https://github.com/ruanyf/document-style-guide)
> extra space in README_zh.md

- 17_foundations.ipynb
Remove self. from function parameter which was not member variable so code runs.
> chapter 17 Model.bwd fix

- utils.py
Added function 'search_images_ddg' to search Duck Duck Go with same api as 'search_images_bing', except for the need for the api-key. Also, this function removes duplicated urls. Accordingly, the paramater is 'max_n'
> Added function 'search_images_ddg' to search Duck Duck Go

- 15_arch_details.ipynb
Fixed as per the solution in https://forums.fast.ai/t/chapter-15-fastai-book-issue-siamese-training-running-mean/84534
> Fix create_head initialization in 15_arch_details.ipynb

- README_id.md
I add the citation and fix minor spelling error on README_id.md
> add citation and fix minor spelling error

- 02_production.ipynb
- clean/02_production.ipynb
The current line of code does not work. It returns an empty array. the edit fixes the problem
> Bing Image Search API Response Modified

- 04_mnist_basics.ipynb
- 05_pet_breeds.ipynb
- clean/04_mnist_basics.ipynb
- clean/05_pet_breeds.ipynb
I'm opening this PR to clarify some confusing things in the book about Cross Entropy Loss
> update explanation of negative log loss (cross entropy loss)

- 06_multicat.ipynb
- clean/06_multicat.ipynb
We don't need to explicitly pass in Imagenet's stats, they are fetched automatically.
> remove Normalize as stats are grabbed automatically

- environment.yml
Fixes "AttributeError: 'FileNotFoundError' object has no attribute read"
See https://stackoverflow.com/a/68586065/3536518
To reproduce original `AttributeError` run `conda env create -f environment.yml`
> environment.yml: Update based on changes to pip

- README.md
- README_bn.md
- README_es.md
- README_id.md
- README_it.md
- README_ko.md
- README_zh.md
As I thank you for everything you have done so far for the DS community, I wanted to contribute by adding the Italian translation.
I am also willing to translate all notebooks if you consider it useful for the community!
> Create italian README and include links

- 16_accel_sgd.ipynb
- notebook not in sync with current fastai library (= leads to confusion)
- rename `begin_*` to  `before_*`, see [`Callback`  documentation](https://docs.fast.ai/callback.core.html#Callback)
> callback begin_* -> before_*

- 19_learner.ipynb
> Add missing words.

- 02_production.ipynb
content-url is no longer valid.
> updated contentUrl in accordance with new Azure JSON structure

- 07_sizing_and_tta.ipynb
> Fix typo: reprsented -> represented

- README.md
- README_bn.md
- README_es.md
- README_id.md
- README_it.md
- README_ja.md
- README_ko.md
- README_pt.md
- README_vn.md
- README_zh.md
Add a Japanese translation of the README.md and a link to the README_ja.md file to all README files.
> Add a Japanese translation of the README.md

- README_ar.md
First contribution:  Arabic course description file has been added "README_ar.md"
> Added_Arabic_Description
